### ISSUE TITLE
touch, key, mouse events

### ISSUE THREAD

**Issue by gedw99** [tfriedel6/canvas#1]
i could not see any examples with events yet ?

Maybe i missed it, but any plans for that.

**Comment by tfriedel6** [comment]
Good point, I will add an example for that.

**Comment by gedw99** [comment]
i saw a few over at the golang SDL package.. Might be easy to adapt one of them ?

https://github.com/veandco/go-sdl2-examples.

He has doe a stellar job on the examples !!!!!

**Comment by tfriedel6** [comment]
I've added a very simple example for mouse and keyboard events for now, and the SDL and GLFW examples also have some very basic input handling in them now

**Comment by gedw99** [comment]
Thank you ! I will definitely have a look and study it.
