### ISSUE TITLE
SDL

### ISSUE THREAD

**Issue by illua1** [tfriedel6/canvas#10]
Sorry, how does it require to install the SDL if I do not use the program for writing on c / c ++?

**Comment by tfriedel6** [comment]
Hi! 
I'm not quite sure I understand what you mean. The canvas/sdlcanvas package uses github.com/veandco/go-sdl2/sdl which binds to the C SDL implementation, so you would have to check there for how the SDL library is installed. You can also use GLFW or something else though if you don't use the canvas/sdlcanvas package, like in some of the examples. 
Hope that helps

**Comment by illua1** [comment]
Yes, I just speak Russian and some translation may not be completely correct.
the fact is that I don’t understand how exactly the SDL needs to be established, so that the canvas would become working
https://cdn.discordapp.com/attachments/324825100216172544/503170957981122560/unknown.png

**Comment by tfriedel6** [comment]
No problem! Ok, it appears that the SDL package requires the SDL library to be installed on the system first. The requirements are listed here:
https://github.com/veandco/go-sdl2#requirements

Alternatively I have just pushed a canvas/glfwcanvas package that you can use instead, which should not require anything to be installed. I hope.
