### ISSUE TITLE
Rect shadow broken

### ISSUE THREAD

**Issue by SuperDog83** [tfriedel6/canvas#11]
Hello again,
Was just experimenting with rect shadows and found out that:

- Rendering shadows is really slow (and uses 100% of my GPU)
- There is a bug when you call DrawImage before rendering the rect

For the bug, here's a screenshot:

![img](https://i.imgur.com/mv29bgB.png)

what's excepted:

![img](https://i.imgur.com/azCxwX2.png)

Here's the code used to draw the rect

```
cnv.Rect(this.X, this.Y, this.W, this.H)
cnv.SetFillStyle(this.Color)
cnv.SetShadowColor(this.ShadowColor)
cnv.SetShadowBlur(this.ShadowBlur)
cnv.SetShadowOffsetX(this.ShadowOffX)
cnv.SetShadowOffsetY(this.ShadowOffY)
cnv.Fill()
```

**Comment by tfriedel6** [comment]
Hi again!

I haven't been able to reproduce the DrawImage problem. Could you maybe post the code with the DrawImage?

As for the performance, that is certainly possible that that can be kinda slow. That's a disadvantage of me using a fairly fast computer, I don't really notice that sometimes. At some point I'll switch to a computer with an embedded GPU and check there.

But just to be sure, did you call cnv.BeginPath() before calling cnv.Rect()? If not, it will actually append the rect to the path every frame. I don't really like that behavior, but it does seem to be the way that the HTML canvas works as well.

**Comment by SuperDog83** [comment]
I have edited the code for the rect, but the issue is still there... :( 

```
		cnv.BeginPath()
		cnv.Rect(this.X, this.Y, this.W, this.H)
		cnv.SetFillStyle(this.Color)
		cnv.SetShadowColor(this.ShadowColor)
		cnv.SetShadowBlur(this.ShadowBlur)
		cnv.SetShadowOffsetX(this.ShadowOffX)
		cnv.SetShadowOffsetY(this.ShadowOffY)
		cnv.Fill()
```

for the drawImage

```
func (this *Image) Render(cnv *canvas.Canvas) {
	cnv.DrawImage(this.Src, this.X, this.Y)
}
```

**Comment by tfriedel6** [comment]
I still haven't been able to reproduce the problem with the DrawImage and the shadow. According to your screenshots, the image should not be drawn at all. Is that right?

As for the performance, the shadows are indeed not all that fast. I hadn't noticed since on my computer they are quite fast, but I tried running it on my phone, and it slows down considerably. There does seem to be a faster way to do blurs, but I'm not sure yet.
