### ISSUE TITLE
Error building on macOS

### ISSUE THREAD

**Issue by beta** [tfriedel6/canvas#14]
I'm running the examples on macOS Mojave 10.14.3, and all throw me the same error:

```
# github.com/tfriedel6/canvas/backend/gogl/gl
ld: framework not found OpenGLES
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

After changing line 19 of `backend/gogl/gl/package.go` from

```go
// #cgo darwin           LDFLAGS: -framework OpenGLES
```

to

```go
// #cgo darwin           LDFLAGS: -framework OpenGL
```

the examples now run successfully. As [Apple's OpenGL ES documentation](https://developer.apple.com/documentation/opengles/) only mentions iOS and tvOS, but no macOS, should OpenGL be used to build on macOS?

**Comment by tfriedel6** [comment]
You're right, thanks! I had only tested compiling for iOS, not for macOS. It should be fixed now.

**Comment by beta** [comment]
Thanks for the quick fix :) I will try again and let you know it it works later today.

**Comment by beta** [comment]
It works! Again thanks for the fix. I'll close this issue now.
