### ISSUE TITLE
Hello, world demo inconsistent

### ISSUE THREAD

**Issue by hunterloftis** [tfriedel6/canvas#15]
Hi! Cool lib. I was testing out the readme example and it seems to miss some fills. Am I doing something wrong? (code unchanged, copy->pasted):

![golang-cross-compile](https://user-images.githubusercontent.com/364501/57574696-c334f200-740b-11e9-9815-5018f054d8cd.png)

**Comment by tfriedel6** [comment]
Hi! Thanks for reporting that. Heh, rather embarrassing that...

It turned out to be related to the self intersecting polygon support I had added recently. It should be fixed now.

**Comment by hunterloftis** [comment]
Beautiful, thanks! :)

![Hello 5_12_2019 2_17_40 PM](https://user-images.githubusercontent.com/364501/57586215-c6d68080-74c0-11e9-841b-d3e308e43569.png)
