### ISSUE TITLE
[suggestion] gomobile display RegisterFilter

### ISSUE THREAD

**Issue by hunterloftis** [tfriedel6/canvas#16]
Would you be open to a contribution that manages mobile canvas display contexts via gomobile's `App` interface filters?

There's currently a lot of ceremony required for using [canvas with gomobile](https://github.com/tfriedel6/canvas/blob/a4826a3e121cb061b6ae6966636256e77fa73ff0/examples/gomobile/gomobile.go). By contrast, you can set up a canvas via sdl or glfw in about [3 lines](https://github.com/tfriedel6/canvas/blob/master/README.md#example).

I've implemented an [App Filter](https://godoc.org/golang.org/x/mobile/app#App) that removes all the manual bookkeeping from using canvas with gomobile via `RegisterFilter`. This is how it's used:

```go
package main

import (
	"golang.org/x/mobile/app"
	"golang.org/x/mobile/event/lifecycle"
	"golang.org/x/mobile/event/paint"

	"github.com/hunterloftis/snake/game"
)

func main() {
	app.Main(func(a app.App) {
		disp := &Display{}
		view := &game.View{}

                // the event filter handles lifecycle bookkeeping
		a.RegisterFilter(disp.Filter)

		for e := range a.Events() {
			switch e := a.Filter(e).(type) {

			case lifecycle.Event:
				if lifecycle.CrossOn == e.Crosses(lifecycle.StageVisible) {
					a.Send(paint.Event{})
				}

			case paint.Event:
				cv := disp.Canvas()
				if cv == nil || e.External {
					continue
				}

				view.DrawOn(cv)
				disp.Paint()
				a.Publish()
				a.Send(paint.Event{})
			}
		}
	})
}
```

**Comment by tfriedel6** [comment]
Sure, that looks great! This would be a new subpackage, right? Would make sense to me since the main package should have as few dependencies as possible.
