### ISSUE TITLE
Is there any plan to support Ellipse for Path2D?

### ISSUE THREAD

**Issue by cosiner** [tfriedel6/canvas#17]
Is there any plan to support Ellipse for Path2D, or could you show me some code snippets to implement it with current API? I just found it was commented or unimplemented.
https://github.com/tfriedel6/canvas/blob/master/path2d.go#L289-L292.

Thanks.

**Comment by tfriedel6** [comment]
Hi, sorry for the delay in responding. I just had some time and managed to implement it and create a new release.
