### ISSUE TITLE
MacOs canvas ratio problem

### ISSUE THREAD

**Issue by ya-tmch** [tfriedel6/canvas#23]
Window size is almost two times bigger than canvas size but width and height are constants that are provided to both canvas and window

**Comment by tfriedel6** [comment]
My guess would be that it has something to do with high DPI displays. Could that be? I've had something like this on iOS before. Unfortunately I don't have a Mac, but I know somebody who does, so when an opportunity arises I will try to look into that.

**Comment by tfriedel6** [comment]
I know it has been a long time, but I have just pushed a new release that addresses this problem. MacOS does indeed scale the window on high DPI displays, which caused the problem. Now the canvas is scaled properly to fill the window, but the actual content scaling is up to the application. I thought about scaling it automatically, but that would have produced some unexpected behavior in GetImageData and PutImageData, so I decided against it.
