### ISSUE TITLE
Blank red screen macOS

### ISSUE THREAD

**Issue by crooliusz** [tfriedel6/canvas#24]
Hi, I have this blank red screen when I try to render something on screen. Weirdly, the only things that are rendered properly are images (DrawImage)
This is a screenshot from the drawing example
<img width="1392" alt="Screenshot 2020-06-01 at 14 59 42" src="https://user-images.githubusercontent.com/29311810/83411573-d0f35600-a418-11ea-982b-8d77356a8679.png">
I'm using
go version go1.14 darwin/amd64
macOS Catalina Version 10.15.4
Do you guys have any idea what might be a problem?

**Comment by tfriedel6** [comment]
Hi, fortunately I have access to a Mac currently and have the same issue. It must be something about the OpenGL driver (this Mac has an Intel graphics chip), as it behaves differently to other drivers. The technical part is that if a vertex attrib array was not enabled, then nothing would get rendered for some reason.

I just published a new version, so you can try that and hopefully it will resolve the issue.
