### ISSUE TITLE
Pixelated text

### ISSUE THREAD

**Issue by Seyz123** [tfriedel6/canvas#25]
Hello, I noticed that when using `fillText` & `strokeText`, the displayed text is pixelated.
Is there some trick or other to overcome this problem?

**Comment by tfriedel6** [comment]
Hi! It should not be, so either it is a bug or the anti-aliasing is off on your system. Could you post a screenshot maybe? And what OS and GPU do you have?

**Comment by Seyz123** [comment]
Hello!  I looked up anti-aliasing and it's definitely there.
I tested it on a server running Debian 9 and attached a screenshot.

![20200604_032438](https://user-images.githubusercontent.com/36236750/83704776-5e01ff00-a613-11ea-9b98-8bb16b456864.png)

**Comment by tfriedel6** [comment]
Ah, I see you're using the software backend. There is a (rather experimental) anti-aliasing setting there. Just set `backend.MSAA` to at least 1 and see what works for you. Higher number should be smoother, but also slower.

The software backend anti-aliasing isn't complete yet and may change a bit in the future, but try if it works for you. If not, you can also just render at twice the size and then scale down the image in the end.

**Comment by Seyz123** [comment]
It worked!  Thanks for your help.
