### ISSUE TITLE
Font size units

### ISSUE THREAD

**Issue by jackwakefield** [tfriedel6/canvas#4]
Are font sizes passed to FillText/MeasureText in pixels or points?

~~If I use `MeasureText` it'll return the width, is the height of the text in pixels the font size?~~
edit: I've since checked the Web API and can see they've added [bounding box ascent/descent measurements](https://html.spec.whatwg.org/multipage/canvas.html#drawing-text-to-the-bitmap).

**Comment by tfriedel6** [comment]
They should be in pixels at the moment. The web API also supports things like points, centimeters, inches and so on, but those depend on the monitor's DPI, and I'm not sure if or how that can be reliably determined.
